export const ADD_SAVED_RECIPE = 'ADD_SAVED_RECIPE';
export const REMOVE_SAVED_RECIPE = 'REMOVE_SAVED_RECIPE';
export const CLEAR_SAVED_RECIPES = 'CLEAR_SAVED_RECIPES';
// For profile picture
export const SET_PROFILE_PIC = 'SET_PROFILE_PIC';
// For inventory
export const STORE_INGREDIENTS = 'STORE_INGREDIENTS';
export const ADD_PANTRY_ITEM = 'ADD_PANTRY_ITEM';
export const REMOVE_PANTRY_ITEM = 'REMOVE_PANTRY_ITEM';
export const CLEAR_PANTRY = 'CLEAR_PANTRY';
// For Explore
export const SET_EXPLORE_RECIPES = 'SET_EXPLORE_RECIPES';
