export const ADD_SAVED_RECIPE = 'ADD_SAVED_RECIPE';
export const REMOVE_SAVED_RECIPE = 'REMOVE_SAVED_RECIPE';
export const CLEAR_SAVED_RECIPES = 'CLEAR_SAVED_RECIPES';
// For profile picture
export const SET_PROFILE_PIC = 'SET_PROFILE_PIC';
